services:
  mysql:
    image: mysql:8.0
    container_name: star_rail_web_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: star_rail_web
      MYSQL_USER: star_rail
      MYSQL_PASSWORD: star_rail_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
